version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9000:9090"
    volumes:
      - ./prometheus-config.yaml:/etc/prometheus/prometheus-config.yaml
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus-config.yaml
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - "3000:3000"
  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml

volumes:
  prometheus-data: