global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: ALBot
    metrics_path: /metrics
    scrape_interval: 1s
    static_configs:
      - targets: ['10.10.3.5:3001'] # Make sure this is my IP-Address
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
